export const chatList = [
  {
    id: 1,
    avatarUrl: "https://media.istockphoto.com/id/1437816897/photo/business-woman-manager-or-human-resources-portrait-for-career-success-company-we-are-hiring.jpg?s=612x612&w=0&k=20&c=tyLvtzutRh22j9GqSGI33Z4HpIwv9vL_MZw_xOE19NQ=",
    name: "Sarah Williams",
    lastMessage: "Looking forward to our coffee date tomorrow! ☕",
    timestamp: "2m ago",
    isRead: false,
  },
  {
    id: 2,
    avatarUrl: "https://images.ctfassets.net/h6goo9gw1hh6/2sNZtFAWOdP1lmQ33VwRN3/24e953b920a9cd0ff2e1d587742a2472/1-intro-photo-final.jpg?w=1200&h=992&fl=progressive&q=70&fm=jpg",
    name: "James Anderson",
    lastMessage: "Sure, I'll be there! Should I bring anything?",
    timestamp: "15m ago",
    isRead: true,
  },
  {
    id: 3,
    avatarUrl: "https://photosbulk.com/wp-content/uploads/instagram-profile-pic-for-girls-cartoon_69.webp",
    name: "Emma Thompson",
    lastMessage: "Hey! How was your weekend? Mine was amazing...",
    timestamp: "1h ago",
    isRead: true,
  },
  {
    id: 4,
    avatarUrl: "https://static3.depositphotos.com/1000951/138/i/450/depositphotos_1380772-stock-photo-profile-of-beautiful-smiling-girl.jpg",
    name: "Michael Chen",
    lastMessage: "The restaurant you recommended was fantastic!",
    timestamp: "3h ago",
    isRead: false,
  },
  {
    id: 5,
    avatarUrl: "https://imgcdn.stablediffusionweb.com/2024/6/12/4d688bcf-f53b-42b6-a98d-3254619f3b58.jpg",
    name: "Sophie Martin",
    lastMessage: "Just landed! Can't wait to meet up 🛬",
    timestamp: "5h ago",
    isRead: true,
  },
  {
    id: 6,
    avatarUrl: "/api/placeholder/48/48",
    name: "David Wilson",
    lastMessage: "How about dinner this Friday?",
    timestamp: "1d ago",
    isRead: true,
  },
  {
    id: 7,
    avatarUrl: "/api/placeholder/48/48",
    name: "Lisa Garcia",
    lastMessage: "That's hilarious 😂 You always make me laugh",
    timestamp: "2d ago",
    isRead: true,
  },
  {
    id: 8,
    avatarUrl: "/api/placeholder/48/48",
    name: "Alex Turner",
    lastMessage: "Did you see the latest episode? No spoilers but...",
    timestamp: "3d ago",
    isRead: true,
  },
  {
    id: 9,
    avatarUrl: "/api/placeholder/48/48",
    name: "Isabella Silva",
    lastMessage: "Perfect! Let's meet at the usual spot",
    timestamp: "5d ago",
    isRead: true,
  },
  {
    id: 10,
    avatarUrl: "/api/placeholder/48/48",
    name: "Ryan Park",
    lastMessage: "Thanks for the great evening! We should do this again",
    timestamp: "1w ago",
    isRead: true,
  },
  {
    id: 11,
    avatarUrl: "/api/placeholder/48/48",
    name: "Sarah Williams",
    lastMessage: "Looking forward to our coffee date tomorrow! ☕",
    timestamp: "2m ago",
    isRead: false,
  },
  {
    id: 12,
    avatarUrl: "/api/placeholder/48/48",
    name: "James Anderson",
    lastMessage: "Sure, I'll be there! Should I bring anything?",
    timestamp: "15m ago",
    isRead: true,
  },
  {
    id: 13,
    avatarUrl: "/api/placeholder/48/48",
    name: "Emma Thompson",
    lastMessage: "Hey! How was your weekend? Mine was amazing...",
    timestamp: "1h ago",
    isRead: true,
  },
  {
    id: 14,
    avatarUrl: "/api/placeholder/48/48",
    name: "Michael Chen",
    lastMessage: "The restaurant you recommended was fantastic!",
    timestamp: "3h ago",
    isRead: false,
  },
  {
    id: 15,
    avatarUrl: "/api/placeholder/48/48",
    name: "Sophie Martin",
    lastMessage: "Just landed! Can't wait to meet up 🛬",
    timestamp: "5h ago",
    isRead: true,
  },
  {
    id: 16,
    avatarUrl: "/api/placeholder/48/48",
    name: "David Wilson",
    lastMessage: "How about dinner this Friday?",
    timestamp: "1d ago",
    isRead: true,
  },
  {
    id: 17,
    avatarUrl: "/api/placeholder/48/48",
    name: "Lisa Garcia",
    lastMessage: "That's hilarious 😂 You always make me laugh",
    timestamp: "2d ago",
    isRead: true,
  },
  {
    id: 18,
    avatarUrl: "/api/placeholder/48/48",
    name: "Alex Turner",
    lastMessage: "Did you see the latest episode? No spoilers but...",
    timestamp: "3d ago",
    isRead: true,
  },
  {
    id: 19,
    avatarUrl: "/api/placeholder/48/48",
    name: "Isabella Silva",
    lastMessage: "Perfect! Let's meet at the usual spot",
    timestamp: "5d ago",
    isRead: true,
  },
  {
    id: 20,
    avatarUrl: "/api/placeholder/48/48",
    name: "Ryan Park",
    lastMessage: "Thanks for the great evening! We should do this again",
    timestamp: "1w ago",
    isRead: true,
  }
];
